options = {
    "lend": "LEND",
    "dodo":"DODO",
    "icx": "ICX",
    "omg": "OMG" , 
    "ksm": "KSM" ,
    "zil": "ZIL" ,
    "dgb": "DGB",
    "eth": "ETH" ,
    "grt": "GRT" , 
    "btt": "BTT" ,
    "band": "BAND" , 
    "vet": "VET" , 
    "xem": "XEM" , 
    "uma" : "UMA" , 
    'xrp': 'XRP' , 
    'yfi': 'YFI' ,
    'strax': 'STRAX' ,
    'atom':'ATOM',
    'dot':'DOT',
    'theta':'THETA',
    'ada': 'ADA' , 
    'rep':'REP',
    'zrx':'ZRX',
    'sc':'SC',
    'pivx':'PIVX',
    'sol':'SOL',
    'npxs':'NPXS',
    'ren':'REN',
    'tomo':'TOMO',
    'bat':'BAT',
    'steem':'STEEM',
    'mkr':'MKR',
    'zec': 'ZEC',
    'qtum': 'QTUM',
    'fil': 'FIL',
    'xmr':'XMR',
    'neo':'NEO',
    'eos':'EOS',
    'trx':'TRX',
    'dash':'DASH',
    'bch':'BCH',
    'link':'LINK',
    'mana': 'MANA',
    'cvc': 'CVC',
    'knc': 'KNC',
    'xlm': 'XLM',
    'snx': 'SNX',
    'etc': 'ETC',
    'xtz': 'XTZ',
    'kava': 'KAVA',
    'miota': 'MIOTA',
    'ltc': 'LTC',
    'uni': 'UNI',
    'bal': 'BAL',
    'btc': 'BTC',
    'lsk': 'LSK',
    'enj': 'ENJ',
    'doge': 'DOGE',
    'comp': 'COMP',
    'bts': 'BTS',
    'paxg': 'PAXG',
    "glm": 'GLM',
    '1inch':'1INCH'



}
